
apiVersion: acme.com/v1
kind: Workload
metadata:
  name: vote-app
image: wingcloudbot/vote-app:sha-{{ .Values.revision }}
route: /vote
replicas: 1
port: 5173
env: 
  VITE_SERVER_URL: http://monadahq.com
  VITE_SERVER_PORT: "80"
command: ["npm", "run", "dev"]